language: cpp
matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - gcc-5
        - g++-5
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7

sudo : required
dist: trusty

# Required packages
before_install:
 - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
 - sudo apt-get update -qq
 
install:
 - sudo apt-get install -qq libboost1.55-all-dev
 - sudo apt-get install -qq cmake
 
# configuration
before_script:
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.7"; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug

# make & check
script:
  - make 
  - make test
