language: cpp
compiler:
  - gcc
  - clang

sudo : required

dist: trusty

# Required packages
before_install:
 - wget --no-check-certificate "https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.sh"
 - sudo bash cmake-3.5.2-Linux-x86_64.sh
 
install:
 - sudo apt-get install -qq libboost1.55-all-dev
 
# configuration
before_script:
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug

# make & check
script:
  - make 
  - make test
