language: cpp

branches:
  only:
    - master
    - develop
    - /^releases\/.*$/

matrix:
  include:

  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - g++-6
    env: COMPILER_CC=gcc-6 COMPILER_CXX=g++-6

  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
    env: COMPILER_CC=gcc-7 COMPILER_CXX=g++-7

  - compiler: clang
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
    env: COMPILER_CC=clang-4.0 COMPILER_CXX=clang++-4.0

sudo : required
dist: trusty

before_install:
 - sudo apt-get update -qq
 - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
 - mkdir ${DEPS_DIR} ; cd ${DEPS_DIR}
 - |
   CMAKE_URL="http://www.cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
   mkdir -p cmake && travis_retry wget --quiet --no-check-certificate  -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
   export PATH=${DEPS_DIR}/cmake/bin:${PATH}
 - cd ..
 
install:
 - sudo apt-get install -qq libboost1.55-all-dev

before_script:
  - export CC=${COMPILER_CC}
  - export CXX=${COMPILER_CXX}
  - mkdir build && cd build
  - cmake --version
  - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug

script:
  - make 
  - make test
